server:
  port: 5000

spring:
  application:
    name: gateway-test

  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.216:8848

    gateway:
      # 自动发现并注册微服务到Nacos
      discovery:
        locator:
          enabled: true
          # 请求服务名配置为小写
          lower-case-service-id: true
          # 自定义路由配置
      routes:
        - id: provider
          uri: lb://provider
          predicates:
            - Path=/provider-demo/**
          filters:
            - StripPrefix=1
        - id: consumer
          uri: lb://consumer
          predicates:
            - Path=/consumer-demo/**
          filters:
            - StripPrefix=1
